---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[CVE-2015-0235]
  - name: fix
    run_list:
    - recipe[CVE-2015-0235::fix]
    - recipe[CVE-2015-0235]
